/* ============================================================
   ORIVON — Portfolio Data
   Orivon — Elijah Sunday, Creative Lead
   ============================================================ */

const DESIGN_WORK = [
    {"id": "eve-wig", "cat": "beauty", "category": "Beauty & Fashion", "year": "2025", "img": "assets/images/Eve Wig Flyer.png", "alt": "Eve Wig Flyer", "title": "Eve Wig Collection"},
    {"id": "millicent", "cat": "beauty", "category": "Beauty & Fashion", "year": "2025", "img": "assets/images/Millicent Elegance and Charm.png", "alt": "Millicent Elegance", "title": "Millicent Elegance & Charm"},
    {"id": "thanksgiving", "cat": "church", "category": "Faith & Church", "year": "2026", "img": "assets/images/Thanksgiving Service May.png", "alt": "Thanksgiving Service", "title": "Thanksgiving Service"},
    {"id": "worship", "cat": "church", "category": "Faith & Church", "year": "2026", "img": "assets/images/Worship Experience.png", "alt": "Worship Experience", "title": "Worship Experience"},
    {"id": "marissa", "cat": "food", "category": "Food & Hospitality", "year": "2025", "img": "assets/images/Marissa's Kitchen 2.png", "alt": "Marissa's Kitchen", "title": "Marissa's Kitchen"},
    {"id": "hotel", "cat": "food", "category": "Food & Hospitality", "year": "2025", "img": "assets/images/Hotel Design.png", "alt": "Hotel Design", "title": "Big John Hotel"},
    {"id": "auditions", "cat": "event", "category": "Events", "year": "2026", "img": "assets/images/Call fo Auditions.png", "alt": "Call for Auditions", "title": "Call for Auditions"},
    {"id": "dog-detectives", "cat": "event", "category": "Events", "year": "2025", "img": "assets/images/Dog Detectives.png", "alt": "Dog Detectives", "title": "Dog Detectives"},
    {"id": "album", "cat": "entertainment", "category": "Entertainment", "year": "2025", "img": "assets/images/Album Back 1.png", "alt": "Album Cover", "title": "Music Album Cover"},
    {"id": "childrens-day", "cat": "social", "category": "Social Media", "year": "2025", "img": "assets/images/Childrens day.png", "alt": "Children's Day", "title": "Children"},
    {"id": "teh-ry", "cat": "social", "category": "Social Media", "year": "2025", "img": "assets/images/Teh_Ry birthday 2.png", "alt": "Birthday Design", "title": "Teh_Ry Birthday"},
    {"id": "birthday-id", "cat": "social", "category": "Social Media", "year": "2026", "img": "assets/images/Birthday Design ID.png", "alt": "Birthday Design", "title": "Birthday Celebration"},
    {"id": "happy-weekend", "cat": "social", "category": "Social Media", "year": "2025", "img": "assets/images/Happy Weekend.png", "alt": "Happy Weekend", "title": "Happy Weekend"},
    {"id": "october", "cat": "social", "category": "Social Media", "year": "2024", "img": "assets/images/OCTOBER DESIGN.jpg", "alt": "October Design", "title": "October Monthly Design"},
    {"id": "april", "cat": "social", "category": "Social Media", "year": "2025", "img": "assets/images/Month of April.png", "alt": "Month of April", "title": "Month of April"},
    {"id": "designz", "cat": "social", "category": "Social Media", "year": "2025", "img": "assets/images/DESIGNZ 1.jpg", "alt": "Designz", "title": "Promotional Design"},
];

const WORD_PROJECTS = [
    {
        id: 'word-1',
        file: 'assets/documents/Business_Proposal_2024.docx',
        title: 'Comprehensive Business Proposal',
        category: 'Business Proposal',
        tag: 'Word Document',
        icon: '📄',
        industry: 'Technology',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 12-page business proposal for a tech startup seeking Series A funding. Includes executive summary, market analysis, competitive landscape, financial projections, and implementation roadmap with professional formatting and branded styling.',
        software: 'Microsoft Word',
        colorPalette: 'Royal Blue, Deep Navy, White',
        typography: 'Calibri, Segoe UI',
        deliverables: '12-page proposal, cover letter, budget appendix',
        challenges: 'Balancing dense financial data with visual clarity while maintaining investor-ready professionalism.',
        solution: 'Implemented a clean grid layout with callout boxes for key metrics, custom tables for financials, and branded headers throughout.',
        pages: 12
    },
    {
        id: 'word-2',
        file: 'assets/documents/Company_Profile_2024.docx',
        title: 'Corporate Company Profile',
        category: 'Company Profile',
        tag: 'Word Document',
        icon: '🏢',
        industry: 'Oil & Gas',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 15-page company profile for an oil and gas firm. Features company history, leadership team, service offerings, project portfolio, and sustainability commitments with professional image integration.',
        software: 'Microsoft Word',
        colorPalette: 'Navy Blue, Gold, White',
        typography: 'Arial, Georgia',
        deliverables: '15-page profile, executive summary card',
        challenges: 'Organizing extensive company history and multiple service lines into a cohesive narrative flow.',
        solution: 'Created sectioned layout with timeline graphics for history, grid layouts for services, and pull quotes for testimonials.',
        pages: 15
    },
    {
        id: 'word-3',
        file: 'assets/documents/Annual_Report_2024.docx',
        title: 'Annual Performance Report',
        category: 'Annual Report',
        tag: 'Word Document',
        icon: '📊',
        industry: 'Finance',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A comprehensive annual report for a financial services company. Includes CEO letter, financial highlights, departmental reviews, growth metrics, and strategic outlook with embedded charts and data tables.',
        software: 'Microsoft Word',
        colorPalette: 'Royal Blue, Silver, White',
        typography: 'Cambria, Calibri',
        deliverables: '20-page report, financial summary sheet',
        challenges: 'Presenting complex financial data in a reader-friendly format without losing accuracy.',
        solution: 'Used structured tables with conditional formatting indicators, infographic-style callouts for KPIs, and clear section hierarchy.',
        pages: 20
    },
    {
        id: 'word-4',
        file: 'assets/documents/Employee_Handbook_2024.docx',
        title: 'Employee Handbook & Policy Manual',
        category: 'Policy Manual',
        tag: 'Word Document',
        icon: '📋',
        industry: 'Healthcare',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 25-page employee handbook for a healthcare organization covering company policies, code of conduct, benefits, leave policies, safety protocols, and disciplinary procedures.',
        software: 'Microsoft Word',
        colorPalette: 'Teal, White, Light Gray',
        typography: 'Segoe UI, Cambria',
        deliverables: '25-page handbook, acknowledgment form, quick reference card',
        challenges: 'Making policy language accessible while maintaining legal compliance and organizational specificity.',
        solution: 'Organized content with a clear table of contents, numbered sections, highlight boxes for key policies, and a quick-reference FAQ section.',
        pages: 25
    },
    {
        id: 'word-5',
        file: 'assets/documents/Marketing_Strategy_2025.docx',
        title: 'Marketing Strategy Document',
        category: 'Marketing Plan',
        tag: 'Word Document',
        icon: '📈',
        industry: 'E-Commerce',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A strategic marketing plan for an e-commerce brand. Includes market research, audience personas, content calendar, channel strategy, KPI framework, and quarterly action plans.',
        software: 'Microsoft Word',
        colorPalette: 'Royal Blue, Coral, White',
        typography: 'Montserrat, Open Sans',
        deliverables: '18-page strategy, content calendar template, KPI dashboard spec',
        challenges: 'Translating abstract marketing concepts into actionable, measurable strategy steps.',
        solution: 'Developed persona-based sections, visual content calendar tables, and SMART goal frameworks with tracking mechanisms.',
        pages: 18
    },
    {
        id: 'word-6',
        file: 'assets/documents/Training_Manual_2025.docx',
        title: 'Training Manual — Onboarding Program',
        category: 'Training Manual',
        tag: 'Word Document',
        icon: '📚',
        industry: 'Technology',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A structured onboarding training manual for a SaaS company. Covers company culture, product overview, tools & systems, role-specific workflows, and assessment checklists.',
        software: 'Microsoft Word',
        colorPalette: 'Purple, Blue, White',
        typography: 'Inter, Merriweather',
        deliverables: '30-page manual, quick-start guide, assessment checklist',
        challenges: 'Creating content that serves both technical and non-technical new hires simultaneously.',
        solution: 'Used progressive complexity structure, visual step-by-step guides, and tiered learning paths for different roles.',
        pages: 30
    },
    {
        id: 'word-7',
        file: 'assets/documents/Project_Report_2025.docx',
        title: 'Project Implementation Report',
        category: 'Project Report',
        tag: 'Word Document',
        icon: '🔧',
        industry: 'Construction',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A detailed project report for a construction firm documenting the completion of a commercial building project. Includes timeline analysis, budget reconciliation, quality assessments, and stakeholder sign-off.',
        software: 'Microsoft Word',
        colorPalette: 'Deep Blue, Orange, White',
        typography: 'Roboto, Georgia',
        deliverables: '14-page report, budget appendix, photo evidence appendix',
        challenges: 'Consolidating data from multiple project phases and stakeholders into a single coherent document.',
        solution: 'Created phased section structure with Gantt-style timeline tables, variance analysis tables, and stakeholder approval sections.',
        pages: 14
    },
    {
        id: 'word-8',
        file: 'assets/documents/Strategic_Plan_2025.docx',
        title: 'Strategic Business Plan',
        category: 'Strategic Plan',
        tag: 'Word Document',
        icon: '🎯',
        industry: 'Education',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A 5-year strategic plan for an educational institution. Covers vision & mission, SWOT analysis, strategic objectives, implementation timeline, resource allocation, and monitoring framework.',
        software: 'Microsoft Word',
        colorPalette: 'Royal Blue, Gold, White',
        typography: 'Garamond, Calibri',
        deliverables: '22-page plan, SWOT analysis matrix, implementation Gantt chart',
        challenges: 'Aligning diverse stakeholder priorities into a unified strategic direction with measurable outcomes.',
        solution: 'Facilitated structured SWOT workshops, developed balanced scorecard framework, and created phased implementation roadmaps.',
        pages: 22
    },
    {
        id: 'word-9',
        file: 'assets/documents/Meeting_Minutes_2026.docx',
        title: 'Meeting Minutes & Resolution Document',
        category: 'Meeting Minutes',
        tag: 'Word Document',
        icon: '📝',
        industry: 'Corporate',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'Professional meeting minutes template and compilation for board meetings. Includes attendance records, agenda items, discussion summaries, action items, and resolution tracking.',
        software: 'Microsoft Word',
        colorPalette: 'Navy, Silver, White',
        typography: 'Calibri, Arial',
        deliverables: 'Template + 6 compiled meeting records, action item tracker',
        challenges: 'Maintaining accuracy and completeness while keeping minutes concise and actionable.',
        solution: 'Designed structured template with clear sections, automated action item extraction, and resolution status tracking.',
        pages: 8
    },
    {
        id: 'word-10',
        file: 'assets/documents/Newsletter_2026.docx',
        title: 'Newsletter — Corporate Quarterly Digest',
        category: 'Newsletter',
        tag: 'Word Document',
        icon: '📰',
        industry: 'Media',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'A visually rich quarterly newsletter for a media company. Features editorial content, team spotlights, industry news, upcoming events, and performance highlights in a multi-column layout.',
        software: 'Microsoft Word',
        colorPalette: 'Royal Blue, Cyan, White',
        typography: 'Playfair Display, Lato',
        deliverables: '8-page newsletter, email-ready PDF version',
        challenges: 'Balancing editorial content density with visual appeal in a Word-based format.',
        solution: 'Implemented multi-column layouts, pull-quote styling, image-text wrap sections, and branded color-coded categories.',
        pages: 8
    }
];

const EXCEL_PROJECTS = [
    {
        id: 'excel-1',
        file: 'assets/documents/Sales_Dashboard_2024.xlsx',
        title: 'Sales Performance Dashboard',
        category: 'Sales Dashboard',
        tag: 'Excel Dashboard',
        icon: '📊',
        industry: 'Retail',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'Interactive sales dashboard tracking revenue, units sold, and growth rates across 12 product categories and 4 regions. Features pivot tables, dynamic charts, conditional formatting, and KPI cards.',
        software: 'Microsoft Excel',
        features: ['Pivot Tables', 'Dynamic Charts', 'Conditional Formatting', 'KPI Cards', 'Slicers'],
        sheets: 5,
        records: '2,400+'
    },
    {
        id: 'excel-2',
        file: 'assets/documents/Financial_Budget_2024.xlsx',
        title: 'Financial Budget & Forecast Model',
        category: 'Finance Dashboard',
        tag: 'Excel Dashboard',
        icon: '💰',
        industry: 'Finance',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'Comprehensive financial model with P&L statement, cash flow projections, and variance analysis. Includes scenario modeling with dropdown selectors and automated chart updates.',
        software: 'Microsoft Excel',
        features: ['Financial Formulas', 'Scenario Manager', 'Named Ranges', 'Data Validation', 'Charts'],
        sheets: 7,
        records: '1,800+'
    },
    {
        id: 'excel-3',
        file: 'assets/documents/Attendance_Payroll_2024.xlsx',
        title: 'Employee Attendance & Payroll System',
        category: 'Payroll System',
        tag: 'Excel Automation',
        icon: '👥',
        industry: 'Human Resources',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'Automated attendance tracking system with leave management, overtime calculation, and payroll processing. Features dropdown menus, date validation, and auto-calculated net pay.',
        software: 'Microsoft Excel',
        features: ['VLOOKUP/INDEX-MATCH', 'Data Validation', 'Conditional Formatting', 'Dropdown Menus', 'Auto-Calculate'],
        sheets: 6,
        records: '500+'
    },
    {
        id: 'excel-4',
        file: 'assets/documents/Inventory_Management_2024.xlsx',
        title: 'Inventory Management Tracker',
        category: 'Inventory System',
        tag: 'Excel Automation',
        icon: '📦',
        industry: 'Manufacturing',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'Real-time inventory tracker with stock level alerts, reorder point calculations, supplier management, and category-wise analysis. Dashboard shows critical stock levels with color-coded indicators.',
        software: 'Microsoft Excel',
        features: ['Conditional Alerts', 'Reorder Formulas', 'Dashboard Charts', 'Named Ranges', 'Validation'],
        sheets: 5,
        records: '3,200+'
    },
    {
        id: 'excel-5',
        file: 'assets/documents/Project_Tracker_2025.xlsx',
        title: 'Project Tracker & Resource Planner',
        category: 'Project Tracker',
        tag: 'Excel Dashboard',
        icon: '📅',
        industry: 'IT Services',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'Multi-project tracker with Gantt-style timeline, resource allocation, milestone tracking, and budget vs actual analysis. Features progress bars and status indicators.',
        software: 'Microsoft Excel',
        features: ['Gantt Chart', 'Progress Bars', 'Resource Allocation', 'Budget Tracking', 'Status Indicators'],
        sheets: 4,
        records: '1,100+'
    },
    {
        id: 'excel-6',
        file: 'assets/documents/CRM_Dashboard_2025.xlsx',
        title: 'CRM & Customer Analytics Dashboard',
        category: 'CRM',
        tag: 'Excel Dashboard',
        icon: '🤝',
        industry: 'Real Estate',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'Customer relationship management system with lead tracking, conversion funnel, communication log, and revenue attribution. Interactive dashboard with slicers for time period and agent filtering.',
        software: 'Microsoft Excel',
        features: ['Funnel Analysis', 'Slicers', 'Pivot Charts', 'Lead Scoring', 'Communication Log'],
        sheets: 6,
        records: '4,500+'
    },
    {
        id: 'excel-7',
        file: 'assets/documents/Expense_Tracker_2025.xlsx',
        title: 'Expense Tracker & Budget Planner',
        category: 'Budget Planner',
        tag: 'Excel Dashboard',
        icon: '💳',
        industry: 'Personal Finance',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'Personal and business expense tracker with category-wise breakdown, monthly trends, budget vs actual comparison, and savings rate calculator. Automated receipt logging with dropdown categories.',
        software: 'Microsoft Excel',
        features: ['Budget vs Actual', 'Trend Charts', 'Category Breakdown', 'Auto-Summary', 'Data Validation'],
        sheets: 4,
        records: '1,500+'
    },
    {
        id: 'excel-8',
        file: 'assets/documents/KPI_Dashboard_2025.xlsx',
        title: 'KPI Performance Dashboard',
        category: 'Performance Dashboard',
        tag: 'Excel Dashboard',
        icon: '🎯',
        industry: 'Healthcare',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'Interactive KPI dashboard for a healthcare organization tracking patient satisfaction, wait times, staff productivity, and departmental performance. Features gauge charts and trend analysis.',
        software: 'Microsoft Excel',
        features: ['KPI Gauges', 'Trend Analysis', 'Conditional Formatting', 'Dynamic Ranges', 'Interactive Slicers'],
        sheets: 5,
        records: '2,000+'
    },
    {
        id: 'excel-9',
        file: 'assets/documents/Invoice_System_2026.xlsx',
        title: 'Invoice & Payment Tracking System',
        category: 'Invoice System',
        tag: 'Excel Automation',
        icon: '🧾',
        industry: 'Professional Services',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'Automated invoice generation and payment tracking system with client database, invoice templates, payment status dashboard, and overdue alerts. Supports multiple currencies and tax calculations.',
        software: 'Microsoft Excel',
        features: ['Invoice Templates', 'Payment Status', 'Overdue Alerts', 'Multi-Currency', 'Tax Calculation'],
        sheets: 5,
        records: '800+'
    },
    {
        id: 'excel-10',
        file: 'assets/documents/Business_Analytics_2026.xlsx',
        title: 'Business Analytics Dashboard',
        category: 'Business Analytics',
        tag: 'Excel Dashboard',
        icon: '📈',
        industry: 'E-Commerce',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'Comprehensive business analytics dashboard combining sales, marketing, customer, and financial data into a single view. Features cross-dimensional analysis, YoY growth, and predictive trend lines.',
        software: 'Microsoft Excel',
        features: ['Cross-Analysis', 'YoY Growth', 'Trend Lines', 'Pivot Tables', 'Power Query'],
        sheets: 8,
        records: '6,000+'
    }
];

const PPT_PROJECTS = [
    {
        id: 'ppt-1',
        file: 'assets/documents/Startup_Pitch_Deck_2024.pptx',
        title: 'Startup Pitch Deck',
        category: 'Pitch Deck',
        tag: 'PowerPoint',
        icon: '🚀',
        industry: 'Technology',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 20-slide investor pitch deck for a fintech startup. Covers problem statement, solution, market size, business model, traction, team, financials, and funding ask with cinematic animations.',
        software: 'Microsoft PowerPoint',
        slides: 20,
        features: ['Animations', 'Custom Icons', 'Charts', 'Timeline', 'Speaker Notes']
    },
    {
        id: 'ppt-2',
        file: 'assets/documents/Corporate_Strategy_2024.pptx',
        title: 'Corporate Strategy Presentation',
        category: 'Corporate Presentation',
        tag: 'PowerPoint',
        icon: '🏢',
        industry: 'Consulting',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 25-slide corporate strategy presentation for a management consulting firm. Includes market analysis, strategic framework, implementation roadmap, and case study with data-driven storytelling.',
        software: 'Microsoft PowerPoint',
        slides: 25,
        features: ['SmartArt', 'Data Charts', 'Roadmap', 'Case Study', 'Transitions']
    },
    {
        id: 'ppt-3',
        file: 'assets/documents/Marketing_Strategy_2024.pptx',
        title: 'Marketing Campaign Strategy Deck',
        category: 'Marketing Strategy',
        tag: 'PowerPoint',
        icon: '📣',
        industry: 'Consumer Goods',
        clientType: 'Freelance Client Project',
        year: '2024',
        description: 'A 22-slide marketing strategy deck covering audience segmentation, channel strategy, content pillars, campaign timeline, budget allocation, and projected ROI with animated infographics.',
        software: 'Microsoft PowerPoint',
        slides: 22,
        features: ['Infographics', 'Animations', 'Channel Mix', 'Budget Charts', 'Timeline']
    },
    {
        id: 'ppt-4',
        file: 'assets/documents/Training_Onboarding_2025.pptx',
        title: 'Employee Training & Onboarding Slides',
        category: 'Training Presentation',
        tag: 'PowerPoint',
        icon: '🎓',
        industry: 'Technology',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A 30-slide training presentation for new employee onboarding. Covers company culture, tools walkthrough, role expectations, compliance, and interactive knowledge check slides.',
        software: 'Microsoft PowerPoint',
        slides: 30,
        features: ['Interactive Slides', 'Icons', 'Progress Tracker', 'Quiz Slides', 'Animations']
    },
    {
        id: 'ppt-5',
        file: 'assets/documents/Investor_Deck_2025.pptx',
        title: 'Investor Relations Annual Review',
        category: 'Investor Deck',
        tag: 'PowerPoint',
        icon: '💹',
        industry: 'Finance',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A 28-slide annual investor review covering financial performance, market position, growth strategy, risk management, and forward guidance with premium data visualization.',
        software: 'Microsoft PowerPoint',
        slides: 28,
        features: ['Financial Charts', 'Waterfall Charts', 'Scenario Analysis', 'Executive Summary', 'Animations']
    },
    {
        id: 'ppt-6',
        file: 'assets/documents/Product_Launch_2025.pptx',
        title: 'Product Launch Presentation',
        category: 'Product Launch',
        tag: 'PowerPoint',
        icon: '✨',
        industry: 'E-Commerce',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A 20-slide product launch deck for an e-commerce platform. Features product demo slides, competitive analysis, go-to-market strategy, pricing tiers, and launch timeline.',
        software: 'Microsoft PowerPoint',
        slides: 20,
        features: ['Product Mockups', 'Comparison Tables', 'Pricing Slides', 'Timeline', 'Speaker Notes']
    },
    {
        id: 'ppt-7',
        file: 'assets/documents/Conference_Keynote_2025.pptx',
        title: 'Conference Keynote Presentation',
        category: 'Conference Presentation',
        tag: 'PowerPoint',
        icon: '🎤',
        industry: 'Education',
        clientType: 'Freelance Client Project',
        year: '2025',
        description: 'A 25-slide keynote presentation for an educational technology conference. Includes thought leadership content, research findings, interactive polls, and actionable takeaways.',
        software: 'Microsoft PowerPoint',
        slides: 25,
        features: ['Full-Bleed Images', 'Animated Text', 'Poll Integration', 'Icon Library', 'Transitions']
    },
    {
        id: 'ppt-8',
        file: 'assets/documents/Sales_Review_2026.pptx',
        title: 'Sales Performance Review Deck',
        category: 'Sales Presentation',
        tag: 'PowerPoint',
        icon: '📊',
        industry: 'Pharmaceutical',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'A 18-slide sales performance review for a pharmaceutical company. Covers quarterly results, territory analysis, pipeline status, win/loss analysis, and strategic recommendations.',
        software: 'Microsoft PowerPoint',
        slides: 18,
        features: ['Sales Funnel', 'Territory Maps', 'Pipeline Charts', 'Win/Loss Analysis', 'KPI Dashboard']
    },
    {
        id: 'ppt-9',
        file: 'assets/documents/Data_Storytelling_2026.pptx',
        title: 'Data Storytelling & Analytics Deck',
        category: 'Data Storytelling',
        tag: 'PowerPoint',
        icon: '📉',
        industry: 'Analytics',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'A 24-slide data storytelling presentation transforming complex datasets into compelling narratives. Features animated chart builds, insight callouts, and decision-recommendation frameworks.',
        software: 'Microsoft PowerPoint',
        slides: 24,
        features: ['Animated Charts', 'Morph Transitions', 'Insight Boxes', 'Decision Trees', 'Speaker Notes']
    },
    {
        id: 'ppt-10',
        file: 'assets/documents/Technology_Overview_2026.pptx',
        title: 'Technology Overview & Innovation Deck',
        category: 'Technology Overview',
        tag: 'PowerPoint',
        icon: '💡',
        industry: 'Technology',
        clientType: 'Freelance Client Project',
        year: '2026',
        description: 'A 22-slide technology overview showcasing a SaaS platform. Covers architecture diagrams, feature highlights, security compliance, integration capabilities, and roadmap with modern design.',
        software: 'Microsoft PowerPoint',
        slides: 22,
        features: ['Architecture Diagrams', 'Feature Grid', 'Security Icons', 'Roadmap', 'Animations']
    }
];

const GALLERY_DETAILS = {
    'eve-wig': {
        title: 'Eve Wig Collection',
        category: 'Beauty & Fashion',
        industry: 'Beauty & Fashion',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A premium product flyer showcasing human hair wig collections with luxury visual composition. Features high-end product photography integration, elegant typography hierarchy, and brand-consistent color treatment across multiple wig categories including lace front, full lace, 360 lace, and closure wigs.',
        objective: 'Create an upscale promotional flyer that conveys the premium quality and variety of the wig collection while maintaining brand elegance.',
        palette: 'Deep Burgundy, Gold, Cream',
        typography: 'Playfair Display, Montserrat',
        challenges: 'Organizing multiple product categories in a single flyer without visual clutter while maintaining luxury appeal.',
        solution: 'Implemented a tiered layout with category sections, subtle gradient backgrounds for each tier, and consistent product frame styling throughout.'
    },
    'millicent': {
        title: 'Millicent Elegance & Charm',
        category: 'Beauty & Fashion',
        industry: 'Beauty & Fashion',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A sophisticated brand identity flyer for a beauty and lifestyle brand. Captures the essence of elegance through refined typography, soft color transitions, and premium visual storytelling.',
        objective: 'Develop a brand launch flyer that establishes Millicent as a premium beauty destination.',
        palette: 'Rose Gold, Cream, Soft Pink',
        typography: 'Bodoni, Lato',
        challenges: 'Conveying both elegance and approachability in a single design language.',
        solution: 'Used rose gold as the unifying accent with soft gradients, paired with serif display fonts for elegance and sans-serif for readability.'
    },
    'thanksgiving': {
        title: 'Thanksgiving Service',
        category: 'Church / Religious',
        industry: 'Faith & Religion',
        clientType: 'Freelance Client Project',
        year: '2026',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'An event flyer for a church thanksgiving service featuring service times, venue details, and pastoral information. Designed with a reverent yet inviting aesthetic that appeals to the congregation.',
        objective: 'Create an announcement flyer that inspires attendance while maintaining the dignity of a worship event.',
        palette: 'Gold, Deep Purple, White',
        typography: 'Cinzel, Raleway',
        challenges: 'Balancing formal religious tone with visual warmth and community appeal.',
        solution: 'Combined gold accents with deep purple backgrounds, used serif display for headers and clean sans-serif for practical details.'
    },
    'worship': {
        title: 'Worship Experience',
        category: 'Church / Religious',
        industry: 'Faith & Religion',
        clientType: 'Freelance Client Project',
        year: '2026',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A worship event flyer with atmospheric lighting effects, bold typography, and event logistics. Created to build anticipation and spiritual excitement for the worship gathering.',
        objective: 'Design a dynamic event flyer that captures the energy and spiritual depth of a worship experience.',
        palette: 'Deep Blue, Gold, White',
        typography: 'Montserrat, Open Sans',
        challenges: 'Creating visual energy in a static design that conveys the dynamic nature of live worship.',
        solution: 'Used radial gradient lighting effects, bold layered typography, and dynamic composition to suggest movement and energy.'
    },
    'marissa': {
        title: "Marissa's Kitchen",
        category: 'Food & Beverage',
        industry: 'Food & Beverage',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A vibrant promotional flyer for a food business specializing in fresh soups. Features appetizing food photography integration, warm color tones, and menu presentation that stimulates appetite.',
        objective: 'Create a mouth-watering promotional design that drives orders and conveys home-cooked quality.',
        palette: 'Warm Orange, Brown, Cream',
        typography: 'Pacifico, Poppins',
        challenges: 'Making the flyer feel both professional and homey at the same time.',
        solution: 'Used warm food photography tones with a handwritten font for the brand name paired with clean sans-serif for menu details.'
    },
    'hotel': {
        title: 'Big John Hotel',
        category: 'Hospitality',
        industry: 'Hospitality',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A professional hotel promotional flyer for Big John Hotel in Eket, Akwa Ibom State. Features location details, contact information, and hospitality imagery designed to attract guests.',
        objective: 'Design a professional hotel flyer that conveys comfort, accessibility, and local hospitality excellence.',
        palette: 'Navy Blue, Gold, White',
        typography: 'Playfair Display, Lato',
        challenges: 'Conveying premium hospitality quality for a local hotel brand.',
        solution: 'Applied luxury hotel design principles with navy and gold palette, professional typography, and clear information hierarchy.'
    },
    'auditions': {
        title: 'Call for Auditions',
        category: 'Event Promotion',
        industry: 'Education / Student',
        clientType: 'Freelance Client Project',
        year: '2026',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'An exciting audition call flyer for a student week event. Features multiple audition categories including vocals and instrumental, with bold call-to-action design and event logistics.',
        objective: 'Generate excitement and maximize audition sign-ups for the student week event.',
        palette: 'Electric Blue, Yellow, Dark',
        typography: 'Bebas Neue, Montserrat',
        challenges: 'Fitting multiple categories and event details while maintaining visual impact.',
        solution: 'Used a bold category grid layout with high-contrast colors and clear visual hierarchy to guide the reader.'
    },
    'dog-detectives': {
        title: 'Dog Detectives',
        category: 'Entertainment',
        industry: 'Entertainment',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'An event promotion flyer for a dog show and entertainment event in Port Harcourt. Features playful yet professional design with event details, venue, and date information.',
        objective: 'Create an eye-catching event flyer that attracts attendees to a unique entertainment event.',
        palette: 'Green, Brown, Cream',
        typography: 'Chunk Five, Open Sans',
        challenges: 'Making a niche event feel exciting and mainstream-appealing.',
        solution: 'Used playful design elements with professional layout structure and clear event information hierarchy.'
    },
    'album': {
        title: 'Music Album Cover',
        category: 'Entertainment',
        industry: 'Entertainment',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A professional music album back cover design featuring track listing, production credits, and artistic visual composition. Designed to complement the front cover and enhance the overall album aesthetic.',
        objective: 'Create a cohesive album back cover that completes the visual narrative of the music project.',
        palette: 'Dark, Gold, Warm Tones',
        typography: 'Custom Display, Avenir',
        challenges: 'Balancing track listing functionality with artistic visual design.',
        solution: 'Used a clean track list layout with artistic background elements, maintaining readability while preserving the artistic vision.'
    },
    'childrens-day': {
        title: "Children's Day",
        category: 'Social Awareness',
        industry: 'Social / Educational',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A meaningful Children\'s Day design featuring an inspirational quote about the importance of children in society. Combines social messaging with visually appealing design.',
        objective: 'Create a shareable social media design that raises awareness and celebrates children.',
        palette: 'Bright Blue, Yellow, Green',
        typography: 'Quicksand, Lato',
        challenges: 'Conveying a serious social message in a design that still feels celebratory and hopeful.',
        solution: 'Paired the impactful quote with bright, hopeful colors and clean typography to balance gravity with optimism.'
    },
    'teh-ry': {
        title: 'Teh_Ry Birthday Celebration',
        category: 'Birthday / Celebration',
        industry: 'Personal',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A heartfelt birthday design featuring a personalized message celebrating creativity and professional excellence. Combines warm personal tone with premium design quality.',
        objective: 'Create a birthday design that feels personal yet professionally crafted.',
        palette: 'Gold, Deep Purple, Cream',
        typography: 'Great Vibes, Montserrat',
        challenges: 'Making a personal birthday message feel premium and visually striking.',
        solution: 'Used elegant script typography for the personal message with premium background treatment and subtle gold accents.'
    },
    'birthday-id': {
        title: 'Birthday Celebration',
        category: 'Birthday / Celebration',
        industry: 'Personal',
        clientType: 'Freelance Client Project',
        year: '2026',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A modern birthday celebration design with date typography, clean layout, and celebratory aesthetic. Features bold numerical date integration and festive design elements.',
        objective: 'Design a visually striking birthday announcement with a modern, clean aesthetic.',
        palette: 'Vibrant Blue, Pink, White',
        typography: 'Bebas Neue, Roboto',
        challenges: 'Creating a unique birthday design that stands out from typical templates.',
        solution: 'Made the date a central design element with oversized typography and clean surrounding layout.'
    },
    'happy-weekend': {
        title: 'Happy Weekend',
        category: 'Social Media',
        industry: 'Social Media',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A weekend greeting social media design featuring the brand contact information. Serves as both a social engagement piece and a subtle brand awareness tool.',
        objective: 'Create an engaging weekend greeting that also reinforces brand visibility and contact information.',
        palette: 'Royal Blue, White, Cyan',
        typography: 'Poppins, Inter',
        challenges: 'Balancing brand promotion with the casual, friendly tone appropriate for a weekend greeting.',
        solution: 'Used the brand color palette with a relaxed layout, placing contact info subtly while the greeting takes center stage.'
    },
    'october': {
        title: 'October Monthly Design',
        category: 'Social Media',
        industry: 'Social Media',
        clientType: 'Freelance Client Project',
        year: '2024',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A visually rich monthly welcome design for October. Features seasonal theming and creative visual composition designed for social media engagement.',
        objective: 'Create a seasonal monthly design that drives engagement and showcases creative range.',
        palette: 'Autumn Orange, Brown, Gold',
        typography: 'Playfair Display, Source Sans',
        challenges: 'Creating a distinctive monthly design that feels fresh while maintaining brand consistency.',
        solution: 'Embraced seasonal color palettes with brand-consistent layout structure and typography hierarchy.'
    },
    'april': {
        title: 'Month of April',
        category: 'Social Media',
        industry: 'Social Media',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A welcoming monthly design for April with fresh spring aesthetics and clean typography. Designed to mark the new month with positivity and visual appeal on social platforms.',
        objective: 'Design a monthly welcome graphic that feels fresh, positive, and shareable.',
        palette: 'Spring Green, Soft Blue, White',
        typography: 'Cormorant, Inter',
        challenges: 'Creating a unique identity for each month while maintaining brand coherence.',
        solution: 'Used spring-themed color palettes with clean typography and the consistent Orivon visual signature.'
    },
    'designz': {
        title: 'Promotional Design',
        category: 'General Promotion',
        industry: 'General',
        clientType: 'Freelance Client Project',
        year: '2025',
        software: 'Adobe Photoshop, CorelDRAW',
        description: 'A general promotional design showcasing creative capabilities with bold typography, contact information integration, and eye-catching visual composition.',
        objective: 'Create a versatile promotional design that demonstrates design skill while serving as a brand awareness piece.',
        palette: 'Royal Blue, White, Black',
        typography: 'Oswald, Open Sans',
        challenges: 'Creating a design that works across multiple contexts and audiences.',
        solution: 'Used a bold, versatile layout with clear contact information and a design that translates well across different social platforms.'
    }
};

const TESTIMONIALS = [
    { quote: "Elijah's designs brought our brand to life. The social media flyers were stunning — premium quality that made our products stand out. Absolutely exceptional work.", initials: 'EM', name: 'Emiz Luxury Hair', role: 'Brand Identity & Social Media' },
    { quote: "The promotional designs exceeded our expectations. Elijah understood our brand vibe immediately and delivered vibrant, eye-catching visuals that drove real engagement.", initials: 'CP', name: 'CRAVE by Princess', role: 'Promotional Design' },
    { quote: "Our luxury fragrance brand needed a designer who could convey elegance through visuals. Elijah delivered precisely that — sophisticated, polished, and on-brand every time.", initials: 'DS', name: 'DEMI Scents', role: 'Product Flyer Design' },
    { quote: "Professional, creative, and incredibly detail-oriented. The Excel dashboard Elijah built transformed our raw data into clear, actionable insights. A true specialist.", initials: 'CO', name: 'Construction Ops Client', role: 'Excel Dashboard & Reporting' },
    { quote: "Elijah's presentation designs elevated our corporate meetings. The slides were visually stunning, well-organized, and told our story with impact. Highly recommended.", initials: 'HL', name: 'Happylizzi Brand', role: 'Brand & Presentation Design' },
    { quote: "From hotel promotional flyers to complete branding packages, Elijah consistently delivers premium quality. His attention to detail and creative eye are unmatched.", initials: 'BJ', name: 'Big John Hotel', role: 'Hospitality Design' }
];
